version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: reps-mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - reps-network

  backend:
    build:
      context: ./backend
    container_name: reps-backend-container
    ports:
      - "8000:8000"
    networks:
      - reps-network
    environment:
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_SENDER: "${EMAIL_SENDER}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_CONTAINER_NAME: "reps-mongo-container"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: reps-frontend-container
    ports:
      - "3000:3000"
    networks:
      - reps-network

volumes:
  mongodb_data:


networks:
  reps-network:
    driver: bridge
